name: reliable-form-pipeline

services:
  postgres:
    image: postgres:18
    container_name: reliable-form-pipeline-postgres
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: reliable-form-pipeline
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
